#!/bin/bash

# variables
xresources=$HOME/.Xresources
session=${1:-plasma}

case $session in
    plasma   ) exec startplasma-x11;;
    spectrwm ) exec spectrwm;;
    bspwm    ) exec bspwm;;
    qtile    ) exec qtile;;
    *        ) exec $1;;
esac

# resources
if [-f $xresources]; then
    xrdb -merge $xresources
fi
