#!/bin/bash

# java re-parenting
export _JAVA_AWT_WM_NONREPARENTING=1

# variables
xresources=$HOME/.Xresources
session=${1:-bspwm}

case $session in
    bspwm    ) exec bspwm;;
    *        ) exec $1;;
esac

# resources
if [-f $xresources]; then
    xrdb -merge $xresources
fi
