#! /bin/sh

# startup programs
sxhkd &
feh --bg-fill $HOME/.config/bspwm/wallpaper/space.jpg &
$HOME/.config/polybar/launch.sh

#
# base
#
bspc config focus_follows_pointer true

# display
bspc monitor eDP -d dev web img file conf
bspc monitor HDMI-A-0 -d VI VII VIII IX X

#
# visual configuration
#
bspc config border_width         0
bspc config window_gap           2

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# colorscheme
bspc config normal_border_color "#1d2021"
bspc config active_border_color "#a89984"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#1d2021"

#
# rules
#
bspc rule -a Sxiv state=floating
bspc rule -a feh state=floating
bspc rule -a Zathura state=tiled

# desktop 1
bspc rule -a kitty desktop='^1' state=tiled follow=on

# desktop 2
bspc rule -a firefox desktop='^2' follow=on

# desktop 3
bspc rule -a Gimp desktop='^3'
bspc rule -a inkscape desktop='^3'

# desktop 4
bspc rule -a Thunar desktop='^4' state=floating

# desktop 5
bspc rule -a Arandr desktop='^5' state=floating
bspc rule -a Pavucontrol desktop='^5' state=floating
bspc rule -a Lxappearance desktop='^5' state=floating

# external
bspc rule -a Stremio desktop='^6' state=fullscreen
