#! /bin/sh

# startup programs
sxhkd &
feh --bg-center $HOME/.config/bspwm/wallpaper/forest.jpg &
$HOME/.config/polybar/launch.sh

#
# base
#
bspc config focus_follows_pointer true

# display
bspc monitor eDP -d 1 2 3 4
bspc monitor HDMI-A-0 -d 5 6 7 8 9 0

#
# visual configuration
#
bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# colorscheme
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# desktop 1
bspc rule -a kitty desktop='^1' follow=on

# desktop 2
bspc rule -a firefox desktop='^2' follow=on

# desktop 3

# desktop 4
bspc rule -a Gimp desktop='^4' state=floating follow=on

# desktop 5

# desktop 6

# desktop 7

# desktop 8

# desktop 9

# desktop 0
