#
# Executes commands at the start of an interactive session.
#

# install prezto
if [ ! -d "$HOME/.zprezto" ]; then
    git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
fi

# source prezto
if [ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# fzf + ripgrep
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh

if hash fd; then
    export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
    export FZF_CTRL_T_COMMAND='fd . $HOME'
    export FZF_ALT_C_COMMAND='fd -t d . $HOME'
else
    echo "Make sure you have fzf and fd installed on your system"
fi

# flutter
#export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
export ANDROID_SDK_ROOT='/opt/android-sdk'

# lsd
alias ls="lsd"
alias la="lsd -la"

# git thingies
alias gittree="git log --all --decorate --graph --oneline"

# lua
alias luamake="~/.lsp/lua-language-server/3rd/luamake/luamake"

# clojure
alias nrepl='clj -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"--interactive'

# makeui
alias makeui='clj -J-Dtest -J-Duser.timezone=UTC -M:dev:clj-tests --watch --fail-fast'

# chruby
# source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
# export PATH="/opt/homebrew/opt/python@3.10/bin:$PATH"

# bun completions
[ -s "/home/crash/.bun/_bun" ] && source "/home/crash/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# virtualenvwrapper
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    export WORKON_HOME="$HOME/.virtualenvs"
    source /usr/bin/virtualenvwrapper_lazy.sh
elif [[ "$OSTYPE" == "darwin"* ]]; then
    source virtualenvwrapper_lazy.sh
fi
