#
# Executes commands at the start of an interactive session.
#

# install prezto
if [ ! -d "$HOME/.zprezto" ]; then
    git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
fi

# source prezto
if [ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# fzf + ripgrep
source "/usr/share/fzf/key-bindings.zsh"
source "/usr/share/fzf/completion.zsh"

if hash fd; then
    export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
    export FZF_CTRL_T_COMMAND='fd . $HOME'
    export FZF_ALT_C_COMMAND='fd -t d . $HOME'
else
    echo "Make sure you have fzf and fd installed on your system"
fi

# lsd
alias ls="lsd"
alias la="lsd -la"
alias mouse="sudo modprobe -r i2c_hid ; sudo modprobe i2c_hid"

# git thingies
alias gittree="git log --all --decorate --graph --oneline"

alias luamake=/home/crash/.lsp/lua-language-server/3rd/luamake/luamake
